### ISSUE TITLE
Investigate expiring Chrome subscriptions

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#154]
[This user](https://app.intercom.io/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/a/web-push-team/conversations/6421080073) is seeing some drop offs in Chrome subscriptions, and linked to [another provider's article](http://www.moengage.com/blog/faq-users-not-receiving-push-notifications/) (see section on User Activity) that mentioned similar issues. It's possible this is an issue in Chrome, but it's worth setting up strict tracking to discover the extent of this issue.

**Comment by gdeglin** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=642139

**Comment by gdeglin** [comment]
Hopefully fixed in 54, as described in the link above. 54 is released on Web, but not on Android yet.

**Comment by tixastronauta** [comment]
@gdeglin @jasonpang as i talked with @jasonpang, re-opening the popup window will re-register the service worker. I also tested simply opening the HTTPS website - it will also re-register the service worker.

**Comment by floffimedia** [comment]
I am dealing with the same issue: My subscriptions in Chrome 56 on Windows 10 will expire after a week or so, and when I resubscribe, the Player ID changes. Here are my logs before and after the expiration: 

`isPushNotificationsEnabledVerbose()

cdn.onesignal.com/sdks/OneSignalSDK.js:1
Called isPushNotificationsEnabled() .

cdn.onesignal.com/sdks/OneSignalSDK.js:1
Called getUserId() .

cdn.onesignal.com/sdks/OneSignalSDK.js:1
Called getRegistrationId() .

cdn.onesignal.com/sdks/OneSignalSDK.js:1
Called isOptedOut() .

undefined

VM125:12
Is Completely Subscribed: true

VM125:13 
VM125:14
What is our OneSignal user ID? 0f05c5d7-df74-4e07-be03-bd87828c6870

VM125:15
What is our push subscription token?
fFlmou7TCF0:APA91bHUPcwQ2Y10Eu5nAM2yfkTI8Hd97GQyjLOsgFHfvcYwcOAfOoWA7uv5MpKObimTDdRlqEAL5fagYSSGtFNADYLoXjCrl3S5iviEivsAzUFaJ0FMY6aZmFR6HZp01OEJr82YPC7j

VM125:16
What is the notification permission status? granted

VM125:17
Are you manually opted out? false

VM125:18
Is a service worker registered and active? (should be false on Safari) true

VM125:19
What is the current URL of this page? https://floffi.media/de/

VM125:20
What environment does OneSignal think it's in? host`

`isPushNotificationsEnabledVerbose()

utils.ts:110
Called isPushNotificationsEnabled() .

utils.ts:110
Called getUserId() .

utils.ts:110
Called getRegistrationId() .

utils.ts:110
Called isOptedOut() .

undefined

VM70:12
Is Completely Subscribed: false

VM70:13 
VM70:14
What is our OneSignal user ID? null

VM70:15
What is our push subscription token? null

VM70:16
What is the notification permission status? granted

VM70:17
Are you manually opted out? false

VM70:18
Is a service worker registered and active? (should be false on Safari) false

VM70:19
What is the current URL of this page? https://floffi.media/de/

VM70:20
What environment does OneSignal think it's in? host`

Unfortunately, I am travelling at the moment, so I only have this one device to run tests.

**Comment by floffimedia** [comment]
Can somebody please point me in the right direction as to how I best investigate this matter?

I’m referring to my last comment. I still don’t know how to reproduce this error, but to me it seems like a huge deal. I can’t have subscriptions expire after a few days, and that’s something that affects the most common browser on the most common OS.

Is it more likely to be an issue with OneSignal, or rather Chrome? Could it be cookies, a service worker / Javascript bug, or maybe a caching problem?

Any help would be greatly appreciated.

**Comment by jasonpang** [comment]
Hey Florian,

This is a tricky bug we haven't found all the causes to yet. I'd like to say this could be simply a result of clearing your browser data, which should produce the same results. Here are some points I can think of:

- Unfortunately, the short answer is that we're not sure. We don't know all the causes for this yet. We've experienced this issue when checking the subscriptions for older testing computers.
- The subscription should last longer than a week though. Our subscriptions usually stay active for at least 2 months (we haven't run any scientific experiments on anything longer). One of our test computers has been displaying a notification daily for at least 2 months.
- Clearing the browser data should produce the result you had (from subscribed perfectly, to everything empty except the notification permission). Whereas the push subscription is cleared when clearing browser data, the notification permission is never reset unless you explicitly do so (on Android, clearing site data and resetting the permission is done together in one button)
Google / Firefox can expire subscriptions for any reason. However, this does not clear the data on your browser locally (the endpoint just becomes invalid, but our SDK does not remove this information).
- Our SDK actually doesn't really ever delete the user ID or any of the information. I've noticed when testing on these older computers, that the site seems to have all its data cleared. The data we store is all gone except for a small amount regenerated each time you visit the test site.

Here are some ways we can test it:

- Ignoring OneSignal for a moment, let's set some data in different kinds of site storage using the script (https://gist.github.com/jasonpang/a690bdae081e230002f2621c909d9f1f). This sets 4 different kinds of storage (HTTP Cache, LocalStorage, IndexedDb, and a persistent cookie), as well as 2 permissions (block them). If you clear your browser data accidentally, they will all go away except the permissions.
- Please run the above script on three HTTPS sites: https://tests.peter.sh/push-generator, https://serviceworke.rs/push-rich_demo.html, https://mdn.github.io/sw-test/. Please try to accept notifications for the first two sites (third one doesn't prompt). The service worker itself is the "5th" storage test to see if things persist.
- If, after a week, any one of the three sites storages is all empty, someone or something (like an extension or cleaner software) is clearing the site storage (or your hard disk is full and Chrome is clearing the storage under pressure). The permissions should remain at "denied" or "blocked", because those do not get reset.
- The script to get the storage state is here: https://gist.github.com/jasonpang/f1c35cd231603167b874905d59355550. You'll need to run it on each of the three listed sites after a week. I didn't include something in this "get-site-storage-data.js" to check the service worker state. You'll just need to navigate to chrome://serviceworker-internals and check for the existence of "Scope: tests.peter.sh", "Scope: serviceworke.rs", "Scope: mdn.github.io".

**Comment by jasonpang** [comment]
This is now tracked internally.

**Comment by loris** [comment]
@jasonpang would you mind sharing any causes you might have found internally? It looks like a more global issue at the Chromium/GCM level and have nothing to do with One Signal, do you confirm?
